const ACCESS_TOKEN = "VUNGANYENKHOACNTT"
const REFRESH_TOKEN = "KSEVRLYNGARENLUXANN"
const TOKEN_TIME_LIFE = "30d" //cần set thời gian vô hạn ví dụ: 30d (30 ngày)

module.exports = {
    ACCESS_TOKEN : ACCESS_TOKEN,
    REFRESH_TOKEN : REFRESH_TOKEN,
    TOKEN_TIME_LIFE : TOKEN_TIME_LIFE
}
